spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_DEV}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME_DEV}
    password: ${SPRING_DATASOURCE_PASSWORD_DEV}

randommer:
  secret-key: ${RANDOMMER_SECRET_KEY}
