spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lv2_final?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 11111111

randommer:
  secret-key: d9af2db97682483dac124a6a59a64325
