name: CD Prod

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: yesjuhee
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64
          tags: |
            yesjuhee/lv3-final:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push-image
    runs-on: prod-self-hosted

    steps:
      - name: change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file from Secrets
        run: |
          echo "Creating .env file from GitHub Secrets"
          echo "${{ secrets.PROD_ENV }}" | base64 --decode > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: yesjuhee
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull latest image and deploy
        run: |
          sudo docker compose -f compose.app.yaml up -d
          sudo docker image prune -af
