name: CI

on:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper using cache
        env:
          SPRING_PROFILES_ACTIVE: test
          RANDOMMER_SECRET_KEY: ${{ secrets.RANDOMMER_SECRET_KEY }}
        run: ./gradlew build --build-cache --no-daemon
